### ISSUE TITLE
Error: Cannot find module './swltch'

### ISSUE THREAD

**Issue by ghost** [yarnaimo/vanilla-clipper#7]
こちらでご報告すべきかわかりませんが、解決できないエラーに出くわし起動できませんでした。

```
internal/modules/cjs/loader.js:638
    throw err;
    ^

Error: Cannot find module './swltch'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:690:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (D:\Program Files\Nodist\bin\node_modules\vanilla-clipper\node_modules\@yarnaimo\twimo\node_modules\@yarnaimo\rain\dist\fp\index.js:18:16)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:690:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (D:\Program Files\Nodist\bin\node_modules\vanilla-clipper\node_modules\@yarnaimo\twimo\node_modules\@yarnaimo\rain\dist\index.js:7:10)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
```

上記はwin10のnodistでのログで、WSL2のUbuntu環境でも試しましたが、同様のエラーが発生しました。

swltchというモジュールの詳細がわからず、手動追加などのアプローチもできませんでした。

**Comment by emc-kk** [comment]
私も同様のエラーが出て調査しましたが、以下のモジュールがlatestでinstallされていることが原因でした。
vanilla-clipper/node_modules/@yarnaimo/twimo/node_modules/@yarnaimo/rain

解決策としては、
vanilla-clipper/node_modules/@yarnaimo/twimo/でのpackage.jsonのrainのversionを0.2.0など旧バージョンにするなどがあるかと思います。
その後、npm installをすれば動くようになるかと。

> こちらでご報告すべきかわかりませんが、解決できないエラーに出くわし起動できませんでした。
> 
> ```
> internal/modules/cjs/loader.js:638
>     throw err;
>     ^
> 
> Error: Cannot find module './swltch'
>     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
>     at Function.Module._load (internal/modules/cjs/loader.js:562:25)
>     at Module.require (internal/modules/cjs/loader.js:690:17)
>     at require (internal/modules/cjs/helpers.js:25:18)
>     at Object.<anonymous> (D:\Program Files\Nodist\bin\node_modules\vanilla-clipper\node_modules\@yarnaimo\twimo\node_modules\@yarnaimo\rain\dist\fp\index.js:18:16)
>     at Module._compile (internal/modules/cjs/loader.js:776:30)
>     at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
>     at Module.load (internal/modules/cjs/loader.js:653:32)
>     at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
>     at Function.Module._load (internal/modules/cjs/loader.js:585:3)
>     at Module.require (internal/modules/cjs/loader.js:690:17)
>     at require (internal/modules/cjs/helpers.js:25:18)
>     at Object.<anonymous> (D:\Program Files\Nodist\bin\node_modules\vanilla-clipper\node_modules\@yarnaimo\twimo\node_modules\@yarnaimo\rain\dist\index.js:7:10)
>     at Module._compile (internal/modules/cjs/loader.js:776:30)
>     at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
>     at Module.load (internal/modules/cjs/loader.js:653:32)
> ```
> 
> 上記はwin10のnodistでのログで、WSL2のUbuntu環境でも試しましたが、同様のエラーが発生しました。
> 
> swltchというモジュールの詳細がわからず、手動追加などのアプローチもできませんでした。

**Comment by saitolume** [comment]
macOS でも同様の不具合が確認されました
